# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_auto_20160519_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user.png', null=True, upload_to='static/'),
        ),
    ]
