# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_auto_20160522_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
